import assert from 'node:assert/strict';
import fs from 'node:fs';

const statistics = fs.readFileSync('resources/js/components/Home/Statistics.vue', 'utf8');
const chart = fs.readFileSync('resources/js/components/Home/StatisticsMiniChart.vue', 'utf8');
const reschedule = fs.readFileSync('resources/js/components/FsrsReschedulePanel.vue', 'utf8');

assert.match(statistics, /axios\.post\('\/statistics\/get'/);
assert.match(statistics, /statistics\/export\/\$\{format\}/);
assert.match(statistics, /period_days/);
assert.match(statistics, /按统一查询缩小范围/);
assert.match(statistics, /开始学习日期（起）/);
assert.match(statistics, /开始学习日期（止）/);
assert.match(statistics, /payload\.date_from = this\.dateFrom/);
assert.match(statistics, /payload\.date_to = this\.dateTo/);
assert.match(statistics, /请选择完整的开始学习日期范围/);
assert.match(statistics, /开始学习日期按学习时区/);
assert.match(statistics, /真实保持率/);
assert.match(statistics, /学习日历/);
assert.match(statistics, /记忆持久度/);
assert.match(statistics, /report\.memory_durability\.states/);
assert.match(statistics, /证据不足的词义不会被标为“掌握稳定”/);
assert.match(statistics, /未来复习压力/);
assert.match(statistics, /明天/);
assert.match(statistics, /未来 7 天/);
assert.match(statistics, /未来 30 天/);
assert.match(statistics, /未来 90 天/);
assert.match(statistics, /不会替你设定每日新学量，也不会修改卡片安排/);
assert.match(statistics, /现在优化记忆模型/);
assert.match(statistics, /确认保存优化结果/);
assert.match(statistics, /优化不会重排已有卡片/);
assert.match(statistics, /getOptimizationStatus/);
assert.match(statistics, /previewOptimization/);
assert.match(statistics, /applyOptimization/);
assert.match(statistics, /仅手动优化/);
assert.match(statistics, /每隔 N 天自动优化/);
assert.match(statistics, /保存自动优化设置/);
assert.match(statistics, /updateOptimizationPolicy/);
assert.match(statistics, /自动优化也不会重排已有卡片/);
assert.match(statistics, /interval_days/);
assert.match(statistics, /FsrsReschedulePanel/);
assert.match(reschedule, /优化参数不会自动改变旧卡片/);
assert.match(reschedule, /确认重排这些卡片/);
assert.match(reschedule, /撤销上次重排/);
assert.doesNotMatch(statistics, /optimized_parameters|current_parameters/);
assert.match(statistics, /@media \(max-width: 700px\)/);
assert.doesNotMatch(statistics, /ReviewLog|fsrs_due_at|review_duration_ms/);
assert.match(chart, /barWidth/);

console.log('M14 statistics UI guard passed: server metrics, unified scope, exports and responsive charts are wired.');
