import assert from 'node:assert/strict';
import fs from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const read = (...parts) => fs.readFileSync(join(root, ...parts), 'utf8');

const pkg = JSON.parse(read('mobile', 'package.json'));
const storage = read('mobile', 'src', 'storage.ts');
const api = read('mobile', 'src', 'api.ts');
const ui = read('mobile', 'src', 'ui.ts');
const mediaCache = read('mobile', 'src', 'mediaCache.ts');
const styles = read('mobile', 'src', 'styles.css');
const swift = read('mobile', 'ios', 'App', 'App', 'SecureTokenPlugin.swift');
const viewController = read('mobile', 'ios', 'App', 'App', 'MyViewController.swift');
const storyboard = read('mobile', 'ios', 'App', 'App', 'Base.lproj', 'Main.storyboard');
const privacy = read('mobile', 'ios', 'App', 'App', 'PrivacyInfo.xcprivacy');
const infoPlist = read('mobile', 'ios', 'App', 'App', 'Info.plist');
const project = read('mobile', 'ios', 'App', 'App.xcodeproj', 'project.pbxproj');
const iosPackage = read('mobile', 'ios', 'App', 'CapApp-SPM', 'Package.swift');
const route = read('routes', 'api.php');
const controller = read('app', 'Http', 'Controllers', 'Mobile', 'MobileTextImportController.php');
const mobileWordSenseController = read('app', 'Http', 'Controllers', 'Mobile', 'MobileWordSenseController.php');
const mobileReadingTargetController = read('app', 'Http', 'Controllers', 'Mobile', 'MobileReadingUnfamiliarTargetController.php');
const readingManualSenseOwner = read('app', 'Services', 'ReadingManualSenseCreationService.php');
const apiContract = read('docs', 'plans', 'mobile-api-v1-contract.md');
const plan = read('docs', 'plans', 'm9-ios-mvp-release-plan.md');
const adr = read('docs', 'adr', 'ADR-0054-m9-ios-mvp-and-release-readiness.md');
const acceptance = read('docs', 'testing', 'm9-ios-mvp-release-acceptance-2026-08-01.md');
const devicePlaybook = read('docs', 'testing', 'm9-ios-device-and-store-acceptance-playbook.md');
const iosGitignore = read('mobile', 'ios', '.gitignore');
const storeMaterials = read('docs', 'release', 'm9-ios-app-store-materials.md');
const privacyNotice = read('docs', 'release', 'mobile-privacy-and-data-deletion.md');
const generatedWebIntegrity = read('mobile', 'scripts', 'ios-generated-web-integrity.mjs');
const xcodeCapabilityWorkflow = read('.github', 'workflows', 'ios-xcode-capability-probe.yml');
const readerAcceptanceWorkflow = read('.github', 'workflows', 'ios-reader-simulator-acceptance.yml');
const readerUiTest = read('mobile', 'ios', 'App', 'AppUITests', 'ReaderAcceptanceUITests.swift');
const appScheme = read('mobile', 'ios', 'App', 'App.xcodeproj', 'xcshareddata', 'xcschemes', 'App.xcscheme');
const readerPabServer = read('tests', 'Support', 'start-ios-reader-pab-server.php');
const commandTimeoutHarness = read('tests', 'Support', 'run-command-with-timeout.php');
const readerSmokeCommand = read('app', 'Console', 'Commands', 'PrepareMobileReaderSmokeData.php');
const offlineSmokeCommand = read('app', 'Console', 'Commands', 'PrepareMobileOfflineSmokeData.php');

assert.equal(pkg.dependencies['@capacitor/core'], '8.4.2');
assert.equal(pkg.dependencies['@capacitor/ios'], '8.4.2');
assert.match(pkg.scripts['cap:sync:ios'], /cap sync ios/);
assert.match(pkg.scripts['ios:generated-web-integrity'], /ios-generated-web-integrity\.mjs/);
for (const dependency of ['Capacitor', 'CapacitorHaptics', 'CapacitorLocalNotifications', 'CapacitorPreferences']) {
  assert.match(iosPackage, new RegExp(dependency));
}
for (const plugin of ['haptics', 'local-notifications', 'preferences']) {
  assert.match(iosPackage, new RegExp(`\.\./\.\./\.\./node_modules/@capacitor/${plugin}`));
}
assert.doesNotMatch(iosPackage, /\\node_modules\\/);

assert.match(storage, /platform === 'android' \|\| platform === 'ios'/);
assert.match(swift, /kSecClassGenericPassword/);
assert.match(swift, /kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly/);
assert.doesNotMatch(swift, /UserDefaults|print\(/);
assert.match(project, /SecureTokenPlugin\.swift in Sources/);
assert.match(project, /MyViewController\.swift in Sources/);
assert.match(viewController, /class MyViewController: CAPBridgeViewController/);
assert.match(viewController, /capacitorDidLoad\(\)/);
assert.match(viewController, /bridge\?\.registerPluginInstance\(SecureTokenPlugin\(\)\)/);
assert.match(storyboard, /customClass="MyViewController"/);
assert.match(storyboard, /customModule="App"/);
assert.match(project, /PrivacyInfo\.xcprivacy in Resources/);
assert.match(privacy, /NSPrivacyAccessedAPICategoryUserDefaults/);
assert.match(privacy, /CA92\.1/);
for (const dataType of ['Name', 'EmailAddress', 'UserID', 'DeviceID', 'OtherUserContent', 'ProductInteraction']) {
  assert.match(privacy, new RegExp(`NSPrivacyCollectedDataType${dataType}`));
}
assert.match(privacy, /<key>NSPrivacyTracking<\/key>\s*<false\/>/);
assert.match(infoPlist, /<key>NSAppTransportSecurity<\/key>\s*<dict>\s*<key>NSAllowsLocalNetworking<\/key>\s*<true\/>\s*<\/dict>/);
assert.match(infoPlist, /<key>NSLocalNetworkUsageDescription<\/key>\s*<string>[^<]*本地学习服务器[^<]*<\/string>/);
assert.doesNotMatch(infoPlist, /NSAllowsArbitraryLoads(?:InWebContent)?/);

assert.match(api, /platform: 'android' \| 'ios' \| 'web'/);
assert.doesNotMatch(api, /\.\.\.payload, platform: 'android'/);
assert.match(api, /markReadingUnfamiliarTarget/);
assert.match(api, /reading_session_id\?: string/);
assert.match(api, /source_revision\?: string/);
assert.match(api, /occurrence_id\?: string/);
assert.match(ui, /ensureReadingSenseContext/);
assert.match(ui, /markReadingUnfamiliarTarget/);
assert.match(ui, /startReadingSession\(\s*chapterId,\s*session\.reading_session_id/);
assert.match(ui, /target\.candidate_word_senses\.push/);
assert.match(ui, /result\.word_sense\.review_card_id/);
assert.match(ui, /token\.canonical_token_index === null \|\| token\.selection_kind === 'phrase'/);
assert.match(route, /\/chapters\/\{chapter\}\/reading-unfamiliar-targets/);
assert.match(mobileReadingTargetController, /ReadingUnfamiliarTargetService/);
assert.match(mobileWordSenseController, /ReadingManualSenseCreationService/);
assert.match(readingManualSenseOwner, /lockManualSenseCreationContext/);
assert.match(readingManualSenseOwner, /RESOLUTION_NEW_SENSE/);
assert.match(readingManualSenseOwner, /LEARNING_ORIGIN_READING/);
assert.match(readingManualSenseOwner, /bindReadingEvidenceToSense/);
assert.doesNotMatch(readingManualSenseOwner, /ReviewLog/);
assert.match(ui, /type="file" accept="\.txt,text\/plain" aria-label="选择文本文件"/);
assert.match(ui, /aria-label="导入资料名称"/);
assert.match(ui, /aria-label="导入章节名称"/);
assert.match(ui, /文本文件必须使用 UTF-8 编码/);
assert.match(ui, /crypto\.subtle\.digest\('SHA-256'/);
assert.match(ui, /pendingTextImport/);
assert.match(ui, /offlineRepository\?\.clear/);
assert.match(ui, /mediaCache\.clear/);
assert.match(mediaCache, /databaseVersion = 2/);
assert.match(mediaCache, /bytes: ArrayBuffer/);
assert.match(mediaCache, /new Blob\(\[entry\.bytes\], \{ type: entry\.mimeType \}\)/);
assert.match(mediaCache, /const bytes = await blob\.arrayBuffer\(\)/);
const arrayBufferIdx = mediaCache.indexOf('const bytes = await blob.arrayBuffer()');
const putObjIdx = mediaCache.indexOf(".objectStore('media').put({", arrayBufferIdx);
assert.ok(putObjIdx !== -1 && arrayBufferIdx < putObjIdx, 'arrayBuffer() must precede the write transaction put()');
assert.doesNotMatch(mediaCache, /bytes:\s*await\s+blob\.arrayBuffer\(\)/, 'inline arrayBuffer inside put object shape is rejected');
assert.doesNotMatch(mediaCache, /\n\s+blob: Blob;/);
assert.match(ui, /正在播放词发音/);
assert.match(ui, /Capacitor\.getPlatform\(\) === 'ios'/);
assert.match(ui, /reader\.readAsDataURL\(blob\)/);
assert.match(ui, /playableAudioSource\(blob\)/);
assert.match(styles, /safe-area-inset-top/);
assert.match(styles, /safe-area-inset-bottom/);

assert.match(route, /\/imports\/text/);
assert.match(controller, /MobileIdempotencyService/);
assert.match(controller, /library\.text_import/);
assert.match(controller, /selected_language !== 'english'/);
assert.match(controller, /'max:200000'/);
assert.match(controller, /ImportService/);
assert.match(apiContract, /POST \/chapters\/\{chapter\}\/reading-unfamiliar-targets/);
assert.match(apiContract, /reading_session_id \+ source_revision \+ occurrence_id/);
assert.match(apiContract, /SOURCE_READING_OCCURRENCE/);
assert.match(apiContract, /READING_TARGET_STALE_SOURCE/);
assert.match(apiContract, /POST \/imports\/text/);
assert.match(apiContract, /library\.text_import/);
assert.match(apiContract, /never retries an ambiguous upload\s+automatically/);

assert.match(adr, /Accepted under current goal authorization/);
assert.match(plan, /Implementation Accepted \/ iOS capability cluster Not Complete/);
for (const source of [plan, adr]) {
  assert.match(source, /Keychain/);
  assert.match(source, /\.txt/);
  assert.match(source, /真实|Real iOS|real iOS/);
}
assert.match(plan, /22 tracked iOS source\/config files/);
assert.match(plan, /must not be staged/);
assert.match(plan, /post-sync integrity\s+gate/);
assert.match(plan, /zero sourcemaps/);
assert.match(plan, /HTTPS, pagination and\s+local-debug safeguards/);
assert.match(storeMaterials, /Status: release candidate; not submitted/);
assert.match(storeMaterials, /Tracking: No/);
assert.match(storeMaterials, /Required external values and evidence before submission/);
assert.match(privacyNotice, /does not track users across apps or websites/);
assert.match(privacyNotice, /## Server data deletion/);
assert.match(privacyNotice, /do not offer or link to account creation/);
assert.match(privacyNotice, /future mobile release\s+adds or links to mobile account creation/);
assert.match(acceptance, /2026-08-06 repository publication revalidation/);
assert.match(acceptance, /currently stale/);
assert.match(acceptance, /contains four sourcemaps/);
assert.match(acceptance, /must run controlled\s+`cap sync ios`/);
assert.match(acceptance, /does not promote the iOS capability cluster to complete/);
for (const ignoredPath of [
  'App/App/public',
  'DerivedData',
  'xcuserdata',
  '*.mobileprovision',
  '*.p12',
  '*.xcarchive',
  'capacitor-cordova-ios-plugins',
  'App/App/capacitor.config.json',
  'App/App/config.xml',
]) {
  assert.match(iosGitignore, new RegExp(ignoredPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
}
assert.match(devicePlaybook, /CODE_SIGNING_ALLOWED=NO/);
assert.match(devicePlaybook, /Post-sync Web asset integrity gate/);
assert.match(devicePlaybook, /referenced JS filenames are identical/);
assert.match(devicePlaybook, /`shasum -a 256` values for index, referenced main JS and referenced CSS are\s+identical/);
assert.match(devicePlaybook, /find ios\/App\/App\/public -name '\*\.map'/);
for (const safeguard of ['正式移动端仅允许 HTTPS', '服务器分页信息无效', '仅用于本地调试']) {
  assert.match(devicePlaybook, new RegExp(safeguard));
}
assert.match(devicePlaybook, /testing environment and dedicated testing database/);
assert.match(devicePlaybook, /Never print or screenshot the bearer token itself/);
assert.match(devicePlaybook, /Only after actual App Store Connect review/);

assert.match(generatedWebIntegrity, /createHash\('sha256'\)/);
assert.match(generatedWebIntegrity, /generated asset set differs/);
assert.match(generatedWebIntegrity, /generated asset hashes differ/);
assert.match(generatedWebIntegrity, /generated iOS public contains sourcemaps/);
for (const safeguard of ['正式移动端仅允许 HTTPS', '服务器分页信息无效', '仅用于本地调试']) {
  assert.match(generatedWebIntegrity, new RegExp(safeguard));
}

assert.match(xcodeCapabilityWorkflow, /workflow_dispatch:/);
assert.match(xcodeCapabilityWorkflow, /workflow_call:/);
assert.match(xcodeCapabilityWorkflow, /actions\/checkout@v6/);
assert.doesNotMatch(xcodeCapabilityWorkflow, /^\s*(?:push|pull_request|schedule):/m);
assert.match(xcodeCapabilityWorkflow, /permissions:\s*\n\s*contents: read/);
assert.match(xcodeCapabilityWorkflow, /runs-on: macos-26/);
assert.match(xcodeCapabilityWorkflow, /Xcode_26\.6\.app/);
assert.match(xcodeCapabilityWorkflow, /npm ci/);
assert.match(xcodeCapabilityWorkflow, /npm test/);
assert.match(xcodeCapabilityWorkflow, /npm run cap:sync:ios/);
assert.match(xcodeCapabilityWorkflow, /npm run ios:generated-web-integrity/);
assert.match(xcodeCapabilityWorkflow, /M9IosMvpGuard\.test\.mjs/);
assert.match(xcodeCapabilityWorkflow, /xcodebuild -resolvePackageDependencies/);
assert.match(xcodeCapabilityWorkflow, /xcrun simctl list devices available/);
assert.match(xcodeCapabilityWorkflow, /generic\/platform=iOS Simulator/);
assert.match(xcodeCapabilityWorkflow, /CODE_SIGNING_ALLOWED=NO/);
assert.match(xcodeCapabilityWorkflow, /xcrun simctl boot /);
assert.match(xcodeCapabilityWorkflow, /xcrun simctl bootstatus/);
assert.match(xcodeCapabilityWorkflow, /xcrun simctl install/);
assert.match(xcodeCapabilityWorkflow, /xcrun simctl launch/);
assert.match(xcodeCapabilityWorkflow, /xcrun simctl terminate/);
assert.match(xcodeCapabilityWorkflow, /xcrun simctl shutdown/);
assert.match(xcodeCapabilityWorkflow, /mobile-dev-inc\/Maestro\/releases\/download\/cli-2\.7\.0\/maestro\.zip/);
assert.match(xcodeCapabilityWorkflow, /a4ccab6b604617e7aef6db4f885666056eabe5cfa32befaa3bc994041b8fcbb5/);
assert.match(xcodeCapabilityWorkflow, /shasum -a 256 -c -/);
assert.match(xcodeCapabilityWorkflow, /Run rendered iOS login-shell smoke/);
assert.match(xcodeCapabilityWorkflow, /IOS · CONNECTED MVP/);
assert.match(xcodeCapabilityWorkflow, /设备令牌由系统 Keychain 保护；应用不会保存密码。/);
assert.match(xcodeCapabilityWorkflow, /inputText: "http:\/\/127\.0\.0\.1:8878"/);
assert.match(xcodeCapabilityWorkflow, /仅用于本地调试；Android\/iOS 正式版可能拒绝明文连接；正式使用应配置 HTTPS。/);
assert.ok(xcodeCapabilityWorkflow.indexOf('Start simulator boot') < xcodeCapabilityWorkflow.indexOf('Install mobile dependencies'));
assert.ok(xcodeCapabilityWorkflow.indexOf('Install mobile dependencies') < xcodeCapabilityWorkflow.indexOf('Wait for simulator and launch app'));
assert.doesNotMatch(xcodeCapabilityWorkflow, /secrets\.|upload-artifact|TestFlight|xcodebuild\s+archive|maestro\s+cloud|MAESTRO_CLOUD|API_KEY/i);

assert.match(readerAcceptanceWorkflow, /workflow_dispatch:/);
assert.match(readerAcceptanceWorkflow, /workflow_call:/);
assert.match(readerAcceptanceWorkflow, /runs-on: macos-26/);
assert.match(readerAcceptanceWorkflow, /system_profiler SPAudioDataType/);
assert.match(readerAcceptanceWorkflow, /Default Output Device: Yes/);
assert.match(readerAcceptanceWorkflow, /IOS_SIM_AUDIO_DEVICE_UNAVAILABLE/);
assert.match(readerAcceptanceWorkflow, /APP_ENV: testing/);
assert.match(readerAcceptanceWorkflow, /DB_CONNECTION: mysql/);
assert.match(readerAcceptanceWorkflow, /TestingDatabaseHealthTest\.php/);
assert.match(readerAcceptanceWorkflow, /run-pab-r3-browser-acceptance\.php/);
assert.match(readerAcceptanceWorkflow, /start-ios-reader-pab-server\.php/);
assert.match(readerAcceptanceWorkflow, /__testing\/acceptance-sentinel/);
assert.match(project, /productType = "com\.apple\.product-type\.bundle\.ui-testing"/);
assert.match(project, /TEST_TARGET_NAME = App/);
assert.match(appScheme, /BlueprintName = "AppUITests"/);
assert.match(readerUiTest, /func testLoginPersistsAuthenticatedSession\(\)/);
assert.match(readerUiTest, /func testReaderPortraitSourceBinding\(\)/);
assert.match(readerUiTest, /func testReaderLandscapePhraseGesture\(\)/);
assert.match(readerUiTest, /func testTextImportThroughSystemFilesPicker\(\)/);
assert.match(readerUiTest, /func testOfflineWarmCaches\(\)/);
assert.match(readerUiTest, /func testOfflineCachedContentAndQueuesGood\(\)/);
assert.match(readerUiTest, /func testOfflinePendingSurvivesRelaunch\(\)/);
assert.match(readerUiTest, /func testOfflineReconnectAutomaticallySyncs\(\)/);
assert.match(readerUiTest, /func testOfflineReconnectEmptyQueueRemainsStable\(\)/);
assert.match(readerUiTest, /pickerFileCell\(named:/);
assert.match(readerUiTest, /app\.cells\.matching\(identifier:/);
assert.match(readerUiTest, /XCTAssertFalse\(rejectedExtension\.isEnabled\)/);
assert.doesNotMatch(readerUiTest, /XCUIApplication\(bundleIdentifier: "com\.apple\.DocumentsApp"\)/);
assert.match(readerUiTest, /app\.buttons\["选择文本文件"\]/);
assert.match(readerUiTest, /文本文件必须使用 UTF-8 编码/);
assert.match(readerUiTest, /文件需为 1–200 KB，且资料和章节名称不能为空/);
assert.match(readerUiTest, /cancelDocumentPicker/);
assert.match(readerUiTest, /XCUIDevice\.shared\.orientation = \.portrait/);
assert.match(readerUiTest, /XCUIDevice\.shared\.orientation = \.landscapeRight/);
assert.match(readerUiTest, /app\.wait\(for: \.runningForeground/);
assert.match(readerUiTest, /private func focusAndType\(/);
assert.match(readerUiTest, /app\.keyboards\.firstMatch/);
assert.match(readerUiTest, /app\.typeText\(text\)/);
assert.doesNotMatch(readerUiTest, /serverField\.typeText|emailField\.typeText|passwordField\.typeText/);
assert.match(readerUiTest, /app\.buttons\["认识 \/ 记得"\]\.waitForExistence/);
assert.match(readerUiTest, /app\.buttons\["不认识"\]\.exists/);
assert.equal((readerUiTest.match(/let app = XCUIApplication\(\)/g) ?? []).length, 9);
assert.doesNotMatch(readerUiTest, /private let app = XCUIApplication\(\)/);
assert.match(readerUiTest, /private func tapReviewControl\(/);
assert.match(readerUiTest, /AUDIO_PLAYBACK_DIAGNOSTICS/);
assert.match(readerUiTest, /LOGIN_DIAGNOSTICS/);
const offlineReviewTapHelper = readerUiTest.match(/private func reviewTapSafeVerticalBounds[\s\S]*?private func scrollUntilHittable/)?.[0] ?? '';
assert.doesNotMatch(offlineReviewTapHelper, /isHittable/);
assert.match(offlineReviewTapHelper, /let navLabels = \["阅读", "复习", "生词", "我的"\]/);
assert.match(offlineReviewTapHelper, /frame\.maxY <= safeBounds\.bottom/);
assert.match(readerUiTest, /app\.staticTexts\[offlineLemma\]\.waitForNonExistence\(timeout: 30\)/);
const offlinePendingRelaunchTest = readerUiTest.match(/func testOfflinePendingSurvivesRelaunch[\s\S]*?func testOfflineReconnectAutomaticallySyncs/)?.[0] ?? '';
assert.match(offlinePendingRelaunchTest, /format: "label BEGINSWITH %@"/);
assert.match(offlinePendingRelaunchTest, /"服务器不可达"/);
assert.match(offlinePendingRelaunchTest, /"1 个操作待同步；0 个操作需要处理。"/);
assert.match(readerUiTest, /press\(\s*forDuration: 0\.7,\s*thenDragTo: landscapeAccount/);
assert.match(readerUiTest, /XCTAssertGreaterThan\(portraitScreenshot\.image\.size\.height, portraitScreenshot\.image\.size\.width\)/);
assert.match(readerUiTest, /XCTAssertGreaterThan\(landscapeScreenshot\.image\.size\.width, landscapeScreenshot\.image\.size\.height\)/);
assert.match(readerUiTest, /app\.tabBars\.buttons\["Browse"\]/);
assert.match(readerUiTest, /navigationBars\.staticTexts\["On My iPhone"\]/);
assert.match(readerUiTest, /app\.staticTexts\["On My iPhone"\]/);
assert.match(readerUiTest, /app\.webViews\.firstMatch/);
assert.match(readerUiTest, /func openTextImportSettings\(app: XCUIApplication\) throws/);
assert.match(readerUiTest, /Missing required UI-test environment variable/);
assert.doesNotMatch(readerUiTest, /XCTSkip/);
assert.match(readerAcceptanceWorkflow, /TEST_RUNNER_LC_SERVER_URL="http:\/\/127\.0\.0\.1:8878"/);
assert.match(readerAcceptanceWorkflow, /TEST_RUNNER_LC_TEST_EMAIL=/);
assert.match(readerAcceptanceWorkflow, /TEST_RUNNER_LC_TEST_PASSWORD=/);
assert.match(readerAcceptanceWorkflow, /TEST_RUNNER_LC_READER_MARKER=/);
assert.match(readerAcceptanceWorkflow, /build-for-testing/);
assert.match(readerAcceptanceWorkflow, /test-without-building/);
assert.match(readerAcceptanceWorkflow, /run_ui_test testLoginPersistsAuthenticatedSession 240/);
assert.ok((readerAcceptanceWorkflow.match(/default: full/g) ?? []).length >= 2);
const loginRunIndex = readerAcceptanceWorkflow.indexOf('run_ui_test testLoginPersistsAuthenticatedSession 240');
const focusBranchIndex = readerAcceptanceWorkflow.indexOf('if [ "$LC_FOCUS" = "full" ]; then');
assert.ok(loginRunIndex !== -1 && focusBranchIndex !== -1 && loginRunIndex < focusBranchIndex);
assert.match(readerAcceptanceWorkflow, /elif \[ "\$LC_FOCUS" = "offline" \]; then/);
assert.match(readerAcceptanceWorkflow, /Unsupported iOS acceptance focus/);
assert.match(readerAcceptanceWorkflow, /run_ui_test testReaderPortraitSourceBinding 300/);
assert.match(readerAcceptanceWorkflow, /run_ui_test testReaderLandscapePhraseGesture 240/);
assert.match(readerAcceptanceWorkflow, /run_ui_test testTextImportThroughSystemFilesPicker 360/);
assert.match(readerAcceptanceWorkflow, /run_ui_test testOfflineWarmCaches 300/);
assert.match(readerAcceptanceWorkflow, /run_ui_test testOfflineCachedContentAndQueuesGood 300/);
assert.match(readerAcceptanceWorkflow, /run_ui_test testOfflinePendingSurvivesRelaunch 180/);
assert.match(readerAcceptanceWorkflow, /run_ui_test testOfflineReconnectAutomaticallySyncs 240/);
assert.match(readerAcceptanceWorkflow, /run_ui_test testOfflineReconnectEmptyQueueRemainsStable 180/);
assert.match(readerAcceptanceWorkflow, /brew install php@8\.4 mysql@8\.4 socat/);
assert.match(readerAcceptanceWorkflow, /LC_BACKEND_PORT=8879/);
assert.match(readerAcceptanceWorkflow, /\/usr\/bin\/afconvert -f m4af -d aac/);
assert.match(readerAcceptanceWorkflow, /TCP-LISTEN:8878,bind=127\.0\.0\.1,reuseaddr,fork TCP:127\.0\.0\.1:8879/);
assert.match(readerAcceptanceWorkflow, /App-facing relay unexpectedly remained reachable after shutdown/);
assert.match(readerAcceptanceWorkflow, /http:\/\/127\.0\.0\.1:8879\/__testing\/acceptance-sentinel/);
assert.match(readerAcceptanceWorkflow, /com\.apple\.DocumentsApp groups/);
assert.match(readerAcceptanceWorkflow, /group\.com\.apple\.FileProvider\.LocalStorage/);
assert.match(readerAcceptanceWorkflow, /File Provider Storage/);
assert.match(readerAcceptanceWorkflow, /invalid-utf8\.txt/);
assert.match(readerAcceptanceWorkflow, /oversize\.txt/);
assert.match(readerAcceptanceWorkflow, /action_type='library\.text_import'/);
assert.match(readerAcceptanceWorkflow, /IMPORT_BOOK_NAME="lc-\$LC_READER_MARKER-valid"/);
assert.match(readerAcceptanceWorkflow, /grep -c 'api\/v1\/mobile\/imports\/text'/);
assert.match(readerAcceptanceWorkflow, /grep -c 'api\/v1\/mobile\/media\/assets\/'/);
assert.match(readerAcceptanceWorkflow, /SYNC_REQUESTS_BEFORE_OFFLINE/);
assert.match(readerAcceptanceWorkflow, /EXPECTED_SYNC_REQUESTS=\$\(\(SYNC_REQUESTS_BEFORE_OFFLINE \+ 1\)\)/);
assert.match(readerAcceptanceWorkflow, /grep -c 'api\/v1\/mobile\/sync\/actions'.*SYNC_REQUESTS_BEFORE_OFFLINE/s);
assert.match(readerAcceptanceWorkflow, /grep -c 'api\/v1\/mobile\/sync\/actions'.*EXPECTED_SYNC_REQUESTS/s);
assert.match(readerAcceptanceWorkflow, /action_type='sense_review\.rating'/);
assert.match(readerAcceptanceWorkflow, /operation_type='sense_review\.rating'/);
assert.match(readerAcceptanceWorkflow, /oc\.transition='apply'/);
assert.doesNotMatch(readerAcceptanceWorkflow, /testReaderSourceBindingAndPhraseGesture/);
assert.match(readerAcceptanceWorkflow, /xcresulttool get test-results summary/);
assert.match(readerAcceptanceWorkflow, /grep -E '\(\/api\/v1\/mobile\|\/__testing\/acceptance-sentinel\)'/);
assert.match(readerAcceptanceWorkflow, /grep -q 'api\/v1\/mobile\/chapters\/\.\*\/reading-unfamiliar-targets'/);
assert.match(readerAcceptanceWorkflow, /grep -q 'api\/v1\/mobile\/word-senses'/);
assert.doesNotMatch(readerAcceptanceWorkflow, /grep -q 'POST\.\*api\/v1\/mobile/);
assert.doesNotMatch(readerAcceptanceWorkflow, /MAESTRO_BIN|maestro\.zip|duration: 60000/);
assert.match(readerAcceptanceWorkflow, /rustup toolchain install 1\.98\.0 --profile minimal --no-self-update/);
assert.match(readerAcceptanceWorkflow, /RUSTUP_TOOLCHAIN=1\.98\.0/);
assert.match(readerAcceptanceWorkflow, /composer\.github\.io\/installer\.sig/);
assert.match(readerAcceptanceWorkflow, /getcomposer\.org\/installer/);
assert.match(readerAcceptanceWorkflow, /hash_file\('sha384'/);
assert.match(readerAcceptanceWorkflow, /composer\.phar.*install --no-interaction --prefer-dist --no-progress/);
assert.match(readerAcceptanceWorkflow, /READING_TARGET_STALE_SOURCE|reading-unfamiliar-targets/);
assert.match(readerAcceptanceWorkflow, /learning_started_origin='reading'/);
assert.match(readerAcceptanceWorkflow, /source='reading_occurrence'/);
assert.match(readerAcceptanceWorkflow, /COUNT\(\*\) FROM review_logs WHERE user_id=\$USER_ID/);
assert.doesNotMatch(readerAcceptanceWorkflow, /^\s*(?:push|pull_request|schedule):/m);
assert.doesNotMatch(readerAcceptanceWorkflow, /sqlite|migrate:fresh|migrate:refresh|migrate:reset|db:wipe|TRUNCATE|DROP DATABASE/i);
assert.doesNotMatch(readerAcceptanceWorkflow, /secrets\.|upload-artifact|TestFlight|xcodebuild\s+archive|maestro\s+cloud|MAESTRO_CLOUD|API_KEY|notify\.ps1/i);
assert.match(readerPabServer, /LINGUACAFE_TEST_SENTINEL/);
assert.match(readerPabServer, /H10IosReaderBindingTest\.php/);
assert.match(readerPabServer, /IOS_READER_PAB_FOCUSED_TEST_FAILED/);
assert.match(readerPabServer, /smoke:mobile-reader-data/);
assert.match(readerPabServer, /LC_OFFLINE_AUDIO_PATH/);
assert.match(readerPabServer, /LC_BACKEND_PORT/);
assert.match(readerPabServer, /smoke:mobile-offline-data/);
assert.match(commandTimeoutHarness, /Symfony\\Component\\Process\\Process/);
assert.match(commandTimeoutHarness, /ProcessTimedOutException/);
assert.match(commandTimeoutHarness, /COMMAND_TIMEOUT_EXCEEDED/);
assert.match(readerSmokeCommand, /app\(\)->environment\('testing'\)/);
assert.match(readerSmokeCommand, /LINGUACAFE_TEST_SENTINEL/);
assert.match(readerSmokeCommand, /__testing_acceptance_sentinel_/);
assert.match(offlineSmokeCommand, /app\(\)->environment\('testing'\)/);
assert.match(offlineSmokeCommand, /LINGUACAFE_TEST_SENTINEL/);
assert.match(offlineSmokeCommand, /WordSenseService/);
assert.match(offlineSmokeCommand, /enrollConfirmedSense/);
assert.match(offlineSmokeCommand, /MediaAssetService/);
assert.match(offlineSmokeCommand, /ROLE_WORD_PRONUNCIATION/);
assert.match(offlineSmokeCommand, /\$lemma = 'offline';/);
assert.match(readerUiTest, /let offlineLemma = "offline"/);
assert.match(readerAcceptanceWorkflow, /OFFLINE_LEMMA="offline"/);
assert.match(offlineSmokeCommand, /initial_fsrs_reps/);

console.log('M9 iOS MVP source and release guard passed.');
