// SenseReviewSessionTracker.js
//
// SenseReview-SessionSummary-1000-1
//
// Pure-function helper for the SenseReview "本次复习总结" (this-session
// summary) feature. No Vue dependency, no network, no persistence.
//
// A "session" represents the ratings a user completed ON THE CURRENT PAGE
// LOAD. It is reset on page refresh (no sessionStorage / localStorage).
// Only real user ratings are recorded — opening the summary, expanding
// blocks, or clicking "继续复习" never writes to the session.
//
// Idempotency: each rating is keyed by a `requestId` (generated by the
// container per rate() call). Recording the same requestId twice is a
// no-op, so double-clicks or accidental re-submits do not inflate stats.
//
// "需要重点注意" (needsAttention) is factual only — no AI:
//   rating === 'again' OR rating === 'hard' OR
//   forgetting_pattern.trend === 'declining'
//
// Shape:
//   session = { entries: Entry[], requestIds: Set<string> }
//   Entry   = { review_card_id, lemma, sense_zh, rating, forgetting_pattern: { trend } }
//   stats   = { total, again, hard, good, easy, needsAttention: Entry[] }

/**
 * Create a fresh empty session.
 * @return {{entries: Array, requestIds: Set<string>}}
 */
export function createSession() {
    return { entries: [], requestIds: new Set() };
}

/**
 * Record one rating into the session. Idempotent: the same requestId is
 * recorded only once. Invalid requestId (undefined / null / '') is
 * rejected to prevent accidental pollution.
 *
 * @param  {object} session     The current session (not mutated).
 * @param  {object} entry       { review_card_id, lemma, sense_zh, rating,
 *                                forgetting_pattern: { trend } }
 * @param  {string} requestId   Unique key for this rating response.
 * @return {object}             New session (immutable update).
 */
export function recordRating(session, entry, requestId) {
    if (!requestId) {
        // Invalid requestId — reject to prevent accidental pollution.
        return session;
    }
    if (session.requestIds.has(requestId)) {
        // Already recorded — idempotent no-op.
        return session;
    }
    if (!entry || !entry.rating) {
        return session;
    }
    const newRequestIds = new Set(session.requestIds);
    newRequestIds.add(requestId);
    return {
        entries: [...session.entries, { ...entry }],
        requestIds: newRequestIds,
    };
}

/**
 * Compute aggregate stats for a session.
 *
 * @param  {object} session
 * @return {{total: number, again: number, hard: number, good: number,
 *           easy: number, needsAttention: Array}}
 */
export function sessionStats(session) {
    const entries = (session && session.entries) || [];
    const stats = {
        total: entries.length,
        again: 0,
        hard: 0,
        good: 0,
        easy: 0,
        needsAttention: [],
    };
    for (const e of entries) {
        switch (e.rating) {
            case 'again': stats.again++; break;
            case 'hard':  stats.hard++;  break;
            case 'good':  stats.good++;  break;
            case 'easy':  stats.easy++;  break;
        }
        const trend = e.forgetting_pattern ? e.forgetting_pattern.trend : null;
        if (e.rating === 'again' || e.rating === 'hard' || trend === 'declining') {
            stats.needsAttention.push({
                review_card_id: e.review_card_id,
                lemma: e.lemma,
                sense_zh: e.sense_zh,
                rating: e.rating,
                trend: trend,
            });
        }
    }
    return stats;
}

/**
 * Whether the user has completed at least one rating in this session.
 * Used to decide whether to show the summary or keep the empty state.
 *
 * @param  {object} session
 * @return {boolean}
 */
export function hasReviewed(session) {
    return !!session && session.entries.length > 0;
}

/**
 * Produce a fresh empty session (alias for createSession, semantically
 * clearer when used mid-page to "start over").
 *
 * @return {{entries: Array, requestIds: Set<string>}}
 */
export function resetSession() {
    return createSession();
}
