<template>
    <!--
        SenseReviewLeechRewritePackageDialog — ADR-0011 (Task A-2)

        Dialog that fetches and displays a rewrite package for a leech
        sense card. The package is generated by the backend at
        POST /reviews/senses/{reviewCardId}/leech/rewrite-package and
        contains a JSON object and a Markdown string intended to be
        copied into an external AI (e.g. ChatGPT, Claude).

        Contract:
         - v-model (Boolean) controls visibility.
         - When opened, fetches the rewrite package via POST.
         - Shows a prominent "no AI" notice at the top.
         - Two tabs: JSON and Markdown, each in a <pre> block.
         - Two copy buttons (JSON / Markdown) using navigator.clipboard.
         - Shows provider_called / card_created / review_log_created as
           chips (all should be false).
         - On error, shows the message but keeps the dialog open.
         - Does NOT call provider-preview. Does NOT auto-create anything.
         - Does NOT mutate frontend state on error.
    -->
    <v-dialog :value="value" max-width="780" @input="$emit('input', $event)">
        <v-card>
            <v-card-title class="d-flex align-center">
                <v-icon small class="mr-2">mdi-package-variant-closed</v-icon>
                重写提示包
                <v-spacer />
                <v-btn icon small @click="close">
                    <v-icon small>mdi-close</v-icon>
                </v-btn>
            </v-card-title>

            <!-- Prominent "no AI" notice. -->
            <v-alert
                type="warning"
                dense
                text
                border="left"
                class="mx-4 mb-0"
            >{{ noAiNoticeText() }}</v-alert>

            <v-card-text>
                <!-- Explicit guarantees. -->
                <div class="d-flex flex-wrap align-center mb-3" style="gap: 6px;">
                    <span class="text-caption text--secondary mr-2">本次操作：</span>
                    <v-chip x-small outlined color="success">不调用 AI</v-chip>
                    <v-chip x-small outlined color="success">不创建学习卡</v-chip>
                    <v-chip x-small outlined color="success">不写复习记录</v-chip>
                </div>

                <!-- Loading state. -->
                <div v-if="loading" class="d-flex align-center justify-center py-6">
                    <v-progress-circular indeterminate size="24" class="mr-3" />
                    <span class="text-body-2 text--secondary">正在生成重写提示包…</span>
                </div>

                <!-- Error state: keep dialog open. -->
                <v-alert
                    v-else-if="error"
                    type="error"
                    dense
                    outlined
                    class="mb-0"
                >{{ error }}</v-alert>

                <!-- Success state. -->
                <template v-else-if="package">
                    <!-- Backend guarantee chips. -->
                    <div class="d-flex flex-wrap align-center mb-3" style="gap: 6px;">
                        <span class="text-caption text--secondary mr-2">后端返回：</span>
                        <v-chip
                            x-small
                            :color="providerCalled ? 'warning' : 'success'"
                            outlined
                        >provider_called: {{ providerCalled ? 'true' : 'false' }}</v-chip>
                        <v-chip
                            x-small
                            :color="cardCreated ? 'warning' : 'success'"
                            outlined
                        >card_created: {{ cardCreated ? 'true' : 'false' }}</v-chip>
                        <v-chip
                            x-small
                            :color="reviewLogCreated ? 'warning' : 'success'"
                            outlined
                        >review_log_created: {{ reviewLogCreated ? 'true' : 'false' }}</v-chip>
                    </div>

                    <v-tabs v-model="activeTab" dense>
                        <v-tab>JSON</v-tab>
                        <v-tab>Markdown</v-tab>
                    </v-tabs>
                    <v-tabs-items v-model="activeTab" class="mt-2">
                        <v-tab-item>
                            <div class="d-flex justify-end mb-2">
                                <v-btn x-small text color="primary" @click="copyJson">
                                    <v-icon x-small left>mdi-content-copy</v-icon>
                                    复制 JSON
                                </v-btn>
                            </div>
                            <pre class="rewrite-pre">{{ jsonText }}</pre>
                        </v-tab-item>
                        <v-tab-item>
                            <div class="d-flex justify-end mb-2">
                                <v-btn x-small text color="primary" @click="copyMarkdown">
                                    <v-icon x-small left>mdi-content-copy</v-icon>
                                    复制 Markdown
                                </v-btn>
                            </div>
                            <pre class="rewrite-pre">{{ markdownText }}</pre>
                        </v-tab-item>
                    </v-tabs-items>
                </template>
            </v-card-text>

            <v-card-actions>
                <v-spacer />
                <v-btn text @click="close">关闭</v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>
</template>

<script>
import {
    noAiNoticeText,
    copyFilename,
} from '../../services/SenseReviewLeechPresentation.js';

export default {
    name: 'SenseReviewLeechRewritePackageDialog',
    props: {
        value: {
            type: Boolean,
            default: false,
        },
        reviewCardId: {
            type: Number,
            required: true,
        },
        lemma: {
            type: String,
            default: '',
        },
    },
    data() {
        return {
            loading: false,
            error: '',
            package: null,
            jsonText: '',
            markdownText: '',
            schemaVersion: null,
            providerCalled: false,
            cardCreated: false,
            reviewLogCreated: false,
            activeTab: 0,
            // Race-protection counter: bumped on every new fetch so stale
            // responses are discarded.
            requestSequence: 0,
        };
    },
    watch: {
        // When the dialog opens, fetch the rewrite package.
        value(open) {
            if (open) {
                this.fetchPackage();
            } else {
                this.resetState();
            }
        },
        // If the reviewCardId changes while the dialog is open (rare but
        // possible), re-fetch.
        reviewCardId(newId, oldId) {
            if (this.value && newId !== oldId) {
                this.fetchPackage();
            }
        },
    },
    methods: {
        fetchPackage() {
            if (!this.reviewCardId) {
                return;
            }
            this.requestSequence++;
            const seq = this.requestSequence;
            this.loading = true;
            this.error = '';
            this.package = null;
            this.jsonText = '';
            this.markdownText = '';
            axios.post('/reviews/senses/' + this.reviewCardId + '/leech/rewrite-package')
                .then((response) => {
                    if (seq !== this.requestSequence) {
                        return;
                    }
                    const data = response.data || {};
                    this.package = data.package || null;
                    this.schemaVersion = data.schema_version || null;
                    // The backend returns separate `json` and `markdown`
                    // fields. Use them directly; fall back to stringifying
                    // the package object if `json` is missing.
                    this.jsonText = typeof data.json === 'string'
                        ? data.json
                        : JSON.stringify(data.package || data.json || {}, null, 2);
                    this.markdownText = typeof data.markdown === 'string'
                        ? data.markdown
                        : '';
                    this.providerCalled = data.provider_called === true;
                    this.cardCreated = data.card_created === true;
                    this.reviewLogCreated = data.review_log_created === true;
                })
                .catch((err) => {
                    if (seq !== this.requestSequence) {
                        return;
                    }
                    // Keep dialog open on error. Do NOT mutate other state.
                    this.error = (err.response && err.response.data && err.response.data.message)
                        || '生成重写提示包失败，请稍后重试。';
                })
                .finally(() => {
                    if (seq !== this.requestSequence) {
                        return;
                    }
                    this.loading = false;
                });
        },
        copyJson() {
            this.copyToClipboard(this.jsonText, 'JSON 已复制到剪贴板。');
        },
        copyMarkdown() {
            this.copyToClipboard(this.markdownText, 'Markdown 已复制到剪贴板。');
        },
        copyToClipboard(text, successMessage) {
            if (!text) {
                return;
            }
            if (navigator && navigator.clipboard && typeof navigator.clipboard.writeText === 'function') {
                navigator.clipboard.writeText(text)
                    .then(() => {
                        this.$emit('copied', { text: successMessage, filename: copyFilename(this.reviewCardId, this.lemma) });
                    })
                    .catch(() => {
                        this.$emit('copied', { text: '复制失败，请手动选择文本复制。', filename: copyFilename(this.reviewCardId, this.lemma) });
                    });
            } else {
                // Fallback for browsers without clipboard API.
                this.$emit('copied', { text: '当前浏览器不支持自动复制，请手动选择文本复制。', filename: copyFilename(this.reviewCardId, this.lemma) });
            }
        },
        close() {
            this.$emit('input', false);
        },
        resetState() {
            this.loading = false;
            this.error = '';
            this.package = null;
            this.jsonText = '';
            this.markdownText = '';
            this.schemaVersion = null;
            this.providerCalled = false;
            this.cardCreated = false;
            this.reviewLogCreated = false;
            this.activeTab = 0;
        },
        // Thin wrapper exposing the pure presentation helper to the template.
        noAiNoticeText,
    },
};
</script>

<style scoped>
.rewrite-pre {
    background: #fafafa;
    border: 1px solid #e0e0e0;
    border-radius: 4px;
    padding: 12px;
    font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
    font-size: 12px;
    line-height: 1.5;
    max-height: 420px;
    overflow: auto;
    white-space: pre-wrap;
    word-break: break-word;
    margin: 0;
}
</style>
